baseUrl: /
theme: terminal
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
author: Nicolas Delauney
title: "Delni :: Blog"
copyright: © 2022 - Nicolas Delauney

# owner = 'Nicolas Delauney'
authorTwitter: Delni_
# paginate = 5
# keywords = ""

params:
  showLanguageSelector: true
  centerTheme: true
  favicon: /images/favicon.png
  logo:
    logoText: Delni
  twitter:
    creator: Delni_
#   ToC = true
#   [params.twitter]
#     creator = "Delni_"
#     site = "https://delni.me"

languages:
  en:
    languageName: 🇺🇸 English
    weight: 1
    readMore: Read more
    menuMore: More
    readOtherPosts: Read other posts
    missingContentMessage: Page not found...
    missingBackButtonLabel: Back to home page

    menu:
      main:
        # - identifier: about
        #   name: About
        #   url: /en/about
        #   weight: 1
        - identifier: tags
          name: Tags
          url: /en/tags
          weight: 2
        # - identifier: posts
        #   name: Posts
        #   url: /en/posts
        #   weight: 3

    params:
      logo:
        logoText: Delni's blog
        logoHomeLink: /en/
  fr:
    languageName: 🇫🇷 Français
    weight: 2
    missingContentMessage: Oups, pas par là !
    missingBackButtonLabel: Retourner au début
    readMore: Lire plus
    menuMore: Plus
    readOtherPosts: Lires les autres articles
    menu:
      main:
        # - identifier: about
        #   name: À propos
        #   url: /fr/about
        #   weight: 1
        - identifier: tags
          name: Tags
          url: /fr/tags
          weight: 2
        # - identifier: posts
        #   name: Articles
        #   url: /fr/posts
        #   weight: 3
    params:
      logo:
        logoText: Delni
        logoHomeLink: /fr/