baseUrl: /
theme: terminal
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
author: Nicolas Delauney
title: "Delni :: Blog"
copyright: © 2022/2023 - Nicolas Delauney
owner: Nicolas Delauney
authorTwitter: Delni_
# paginate = 5
# keywords = ""

taxonomies:
  tag: tags
  category: categories
  serie: series

params:
  showLanguageSelector: true
  showLastUpdated: false
  oneHeadingSize: false
  centerTheme: true
  ToC: false
  favicon: /images/favicon.png
  logo:
    logoText: Delni
  twitter:
    creator: Delni_
#   ToC = true
#   [params.twitter]
#     creator = "Delni_"
#     site = "https://delni.me"

languages:
  en:
    languageName: 🇺🇸 English
    weight: 1
    readMore: Read more
    menuMore: More
    readOtherPosts: Read other posts
    readOtherPostsInSerie: Read other posts in this serie
    missingContentMessage: Page not found...
    missingBackButtonLabel: Back to home page

    menu:
      main:
        - identifier: about
          name: About
          url: /en/about
          weight: 1
        - identifier: posts
          name: Posts
          url: /en/posts
          weight: 2
        - identifier: tags
          name: Tags
          url: /en/tags
          weight: 3
        - identifier: series
          name: Series
          url: /en/series
          weight: 4

    params:
      logo:
        logoText: Delni's blog
        logoHomeLink: /en/
  fr:
    languageName: 🇫🇷 Français
    weight: 2
    missingContentMessage: Oups, pas par là !
    missingBackButtonLabel: Retourner au début
    readMore: Lire plus
    menuMore: Plus
    readOtherPosts: Lire les autres articles
    readOtherPostsInSerie: Lire les autres articles de cette série
    TocTitle: Sommaire
    menu:
      main:
        - identifier: about
          name: À propos
          url: /fr/about
          weight: 1
        - identifier: tags
          name: Tags
          url: /fr/tags
          weight: 3
        - identifier: posts
          name: Articles
          url: /fr/posts
          weight: 2
        - identifier: series
          name: Séries
          url: /fr/series
          weight: 4
    params:
      logo:
        logoText: Delni
        logoHomeLink: /fr/