# Where should we write the GIF?
Output gitlg.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 20
Set Width 1200
Set Height 600

# Do this to let terminal startup
Hide
Sleep 1s
Ctrl+L
Sleep 1s
Show
# Type a command in the terminal.
Type "git lg"

# Pause for dramatic effect...
Sleep 1s

# Run the command by pressing enter.
Enter

Sleep 5s
Down@500ms 4
Sleep 5s
Up@500ms 4
Sleep 5s
# Type a command in the terminal.
Type "q"

# Pause for dramatic effect...
Sleep 2s
Ctrl+L
Sleep 2s