name: Deploy Blog

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Latest version
      uses: actions/checkout@v3
    - name: Hugo Build
      uses: jakejarvis/hugo-build-action@v0.101.0
    - uses: actions/upload-artifact@master
      with:
        name: blog
        path: './public'