name: Deploy Blog

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Latest version
      uses: actions/checkout@v3
    - name: Hugo Build
      uses: jakejarvis/hugo-build-action@v0.101.0
    - uses: actions/upload-artifact@master
      with:
        name: blog
        path: './public'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@master
      with:
        name: blog
        path: './public'
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -az --delete-after --rsync-path "sudo /usr/bin/rsync"
        path: './public/'
        remote_path: ${{ secrets.DEPLOY_PATH }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_SSH_KEY }}